
[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[general]
import = ["/home/quentin/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
